/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public final class roc_algorithm_options {
  public final static int ROC_NO_ALGORITHM_OPTIONS = rocJNI.ROC_NO_ALGORITHM_OPTIONS_get();
  public final static int ROC_STANDARD_REPRESENTATION = rocJNI.ROC_STANDARD_REPRESENTATION_get();
  public final static int ROC_FAST_REPRESENTATION = rocJNI.ROC_FAST_REPRESENTATION_get();
  public final static int ROC_PERIOCULAR_REPRESENTATION = rocJNI.ROC_PERIOCULAR_REPRESENTATION_get();
  public final static int ROC_TATTOO_REPRESENTATION = rocJNI.ROC_TATTOO_REPRESENTATION_get();
  public final static int ROC_FRONTAL_DETECTION = rocJNI.ROC_FRONTAL_DETECTION_get();
  public final static int ROC_FULL_DETECTION = rocJNI.ROC_FULL_DETECTION_get();
  public final static int ROC_PERIOCULAR_DETECTION = rocJNI.ROC_PERIOCULAR_DETECTION_get();
  public final static int ROC_ROLL_DETECTION = rocJNI.ROC_ROLL_DETECTION_get();
  public final static int ROC_PREFER_LARGER_DETECTIONS = rocJNI.ROC_PREFER_LARGER_DETECTIONS_get();
  public final static int ROC_MANUAL_DETECTION = rocJNI.ROC_MANUAL_DETECTION_get();
  public final static int ROC_PAD_LOGO = rocJNI.ROC_PAD_LOGO_get();
  public final static int ROC_PITCHYAW = rocJNI.ROC_PITCHYAW_get();
  public final static int ROC_ANALYTICS = rocJNI.ROC_ANALYTICS_get();
  public final static int ROC_LANDMARKS = rocJNI.ROC_LANDMARKS_get();
  public final static int ROC_LIPS = rocJNI.ROC_LIPS_get();
  public final static int ROC_THUMBNAIL = rocJNI.ROC_THUMBNAIL_get();
  public final static int ROC_SPOOF_FF = rocJNI.ROC_SPOOF_FF_get();
  public final static int ROC_SPOOF_AF = rocJNI.ROC_SPOOF_AF_get();
  public final static int ROC_SERIAL = rocJNI.ROC_SERIAL_get();
  public final static int ROC_TEMPLATE_VERSION = rocJNI.ROC_TEMPLATE_VERSION_get();
  public final static int ROC_FR_COMPATIBILITY_VERSION = rocJNI.ROC_FR_COMPATIBILITY_VERSION_get();
  public final static int ROC_TATTOO_COMPATIBILITY_VERSION = rocJNI.ROC_TATTOO_COMPATIBILITY_VERSION_get();
  public final static int ROC_TEMPLATE_VERSION_MASK = rocJNI.ROC_TEMPLATE_VERSION_MASK_get();
}

