/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class SWIGTYPE_p_roc_algorithm_options {
  private transient long swigCPtr;

  public SWIGTYPE_p_roc_algorithm_options(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_roc_algorithm_options() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_roc_algorithm_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

