/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public final class roc_color_space {
  public final static int ROC_GRAY8 = rocJNI.ROC_GRAY8_get();
  public final static int ROC_BGR24 = rocJNI.ROC_BGR24_get();
}

