/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_embedded_gender {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_embedded_gender(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_embedded_gender obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_embedded_gender(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFemale(float value) {
    rocJNI.roc_embedded_gender_female_set(swigCPtr, this, value);
  }

  public float getFemale() {
    return rocJNI.roc_embedded_gender_female_get(swigCPtr, this);
  }

  public void setMale(float value) {
    rocJNI.roc_embedded_gender_male_set(swigCPtr, this, value);
  }

  public float getMale() {
    return rocJNI.roc_embedded_gender_male_get(swigCPtr, this);
  }

  public roc_embedded_gender() {
    this(rocJNI.new_roc_embedded_gender(), true);
  }

}
