version: 2
registries:
    google:
        type: maven-repository
        url: "https://dl.google.com/dl/android/maven2"
    maven-central:
        type: maven-repository
        url: "https://repo.maven.apache.org/maven2"
    gradle-plugin-portal:
        type: maven-repository
        url: "https://plugins.gradle.org/m2"
    sonatype:
        type: maven-repository
        url: "https://oss.sonatype.org/content/repositories/snapshots"
    commonsware:
        type: maven-repository
        url: "https://s3.amazonaws.com/repo.commonsware.com"
updates:
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "weekly"

    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
