# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: circleci/android:api-29-ndk
      
pipelines:
  default:       
    - parallel:
        - step:
            name: "Run clientapi unit tests"
            caches:
              - gradle
            script: 
              - ./ci/pipeline/setup
              - ./gradlew id:bundleDebugClasses && ./gradlew clientapi:testDebugUnitTest
            artifacts:
              - clientapi/build/reports/tests/testDebugUnitTest/*
        - step:
            name: "Run id unit tests"
            caches:
              - gradle
            script: 
              - ./ci/pipeline/setup
              - ./gradlew id:bundleDebugClasses && ./gradlew id:testDebugUnitTest
            artifacts:
              - id/build/reports/tests/testDebugUnitTest/*
        - step:
            name: "Run face unit tests"
            caches:
              - gradle
            script: 
              - ./ci/pipeline/setup
              - ./gradlew id:bundleDebugClasses && ./gradlew face:testDebugUnitTest
            artifacts:
              - face/build/reports/tests/testDebugUnitTest/*           
        - step:
            name: "Run fingerprint unit tests"
            caches:
              - gradle
            script: 
              - ./ci/pipeline/setup
              - ./gradlew id:bundleDebugClasses && ./gradlew fingerprint:testDebugUnitTest
            artifacts:
              - fingerprint/build/reports/tests/testDebugUnitTest/*
