# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: circleci/android:api-29-ndk
      
pipelines:
  default:       
      - step:
          name: "Build and sign universal apk"
          caches:
            - gradle
          script: 
            - bash ./ci/pipeline/setup
            - cat ci/debug_gradle_signing >> id/build.gradle && ./gradlew bundleDebug --stacktrace
            - wget "https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all.jar"
            - java -jar bundletool-all.jar build-apks --bundle id/build/outputs/bundle/debug/id-debug.aab --output universal.apks --overwrite --mode=UNIVERSAL --ks=ci/debug_keystore --ks-key-alias=androiddebugkey --key-pass=pass:android --ks-pass=pass:android
            - mv universal.apks universal.zip
            - unzip universal.zip
                      
          artifacts:
            - universal.apk

