# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
    depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
    caches:
        gradlewrapper: ~/.gradle/wrapper
        android: ~/android
    steps:

        ######################################################################
        # Run the Client API unit tests with coverage and upload report to
        # artifacts.
        ######################################################################
        -   step: &run-clientapi-unit-tests
                name: "Run Clientapi unit tests"
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                    - android
                script:
                    - export ANDROID_SDK_ROOT=$PWD/android && export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin && export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/sdks/ndk-bundle
                    - . ./ci/pipeline/setup
                    - ls $ANDROID_SDK_ROOT/sdks
                    - ls $ANDROID_SDK_ROOT/sdks/ndk-bundle
                    - ./gradlew clientapi:jacocoTestReportStandardDebug
                artifacts:
                    - clientapi/build/reports/**

        ######################################################################
        # Run the ID unit tests with coverage and upload report to artifacts.
        ######################################################################
        -   step: &run-id-unit-tests
                name: "Run Id & Core unit tests"
                size: 2x
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew core:jacocoTestReportDebug
                    - ./gradlew id:jacocoTestReportStandardDebug
                artifacts:
                    - id/build/reports/**
                    - core/build/reports/**

        ######################################################################
        # Run the Face unit tests with coverage and upload report to artifacts.
        ######################################################################
        -   step: &run-face-unit-tests
                name: "Run Face unit tests"
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew face:jacocoTestReportStandardDebug --no-daemon
                artifacts:
                    - face/build/reports/**

        ######################################################################
        # Run the Fingerprint unit tests with coverage and upload report to
        # artifacts.
        ######################################################################
        -   step: &run-fingerprint-unit-tests
                name: "Run Fingerprint unit tests"
                max-time: 30
                size: 2x
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew fingerprint:jacocoTestReportStandardDebug
                artifacts:
                    - fingerprint/build/reports/**

        ######################################################################
        # Run the Fingerprint Scanner unit tests with coverage and upload
        # report to artifacts.
        ######################################################################
        -   step: &run-fingerprintscanner-unit-tests
                name: "Run Fingerprint Scanner unit tests"
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    # Tests lock if gradle runs in parallel
                    - echo "org.gradle.parallel=false" >> gradle.properties
                    - ./gradlew fingerprintscanner:jacocoTestReportDebug
                artifacts:
                    - fingerprintscanner/build/reports/**

        ######################################################################
        # Get all of the test and coverage reports from artifacts, upload
        # them to sonarcloud.io, and check that they pass the quality gateway.
        ######################################################################
        -   step: &upload-sonar-scan-and-check-quality-gate
                max-time: 30
                name: "Upload scan and check quality gateway"
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew sonarqube -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=3600

        ######################################################################
        # Build all of the test APKs for the different modules, then Download
        # the google bundle tool, and use it to create an universal
        # APK and upload it to artifacts.
        ######################################################################
        -   step: &build-and-sign-universal-apk
                name: "Build universal & test APKs"
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    # Build ID Android Test APK
                    - ./gradlew id:assembleStandardDebugAndroidTest
                    - mv id/build/outputs/apk/androidTest/standard/debug/id-standard-debug-androidTest.apk id-standard-debug-androidTest.apk
                    # Build Client API Android Test APK
                    - ./gradlew clientapi:assembleStandardDebugAndroidTest
                    - mv clientapi/build/outputs/apk/androidTest/standard/debug/clientapi-standard-debug-androidTest.apk clientapi-standard-debug-androidTest.apk
                    # Build Fingerprint Android Test APK
                    - ./gradlew fingerprint:assembleStandardDebugAndroidTest
                    - mv fingerprint/build/outputs/apk/androidTest/standard/debug/fingerprint-standard-debug-androidTest.apk fingerprint-standard-debug-androidTest.apk
                    # Build Face Android Test APK
                    - ./gradlew face:assembleStandardDebugAndroidTest
                    - mv face/build/outputs/apk/androidTest/standard/debug/face-standard-debug-androidTest.apk face-standard-debug-androidTest.apk
                    # Build Universal APK
                    - ./gradlew bundleStandardDebug --stacktrace
                    - wget "https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all.jar"
                    - java -jar bundletool-all.jar build-apks --bundle id/build/outputs/bundle/standardDebug/id-standard-debug.aab --output universal.apks --overwrite --mode=UNIVERSAL --ks=debug.keystore --ks-key-alias=androiddebugkey --key-pass=pass:android --ks-pass=pass:android
                    - mv universal.apks universal.zip
                    - unzip universal.zip
                artifacts:
                    - universal.apk
                    - id-standard-debug-androidTest.apk
                    - clientapi-standard-debug-androidTest.apk
                    - fingerprint-standard-debug-androidTest.apk
                    - face-standard-debug-androidTest.apk

        ######################################################################
        # Run All Android tests on Firebase test lab.
        ######################################################################
        -   step: &run-all-android-tests
                name: "Run android tests"
                max-time: 60
                image: google/cloud-sdk:slim
                script:
                    - bash ./ci/pipeline/setup_gcloud
                    - mv ./*.apk ./ci/pipeline/
                    - cd ./ci/pipeline/
                    - ./run_all_android_tests.sh universal.apk id:id-standard-debug-androidTest.apk fingerprint:fingerprint-standard-debug-androidTest.apk face:face-standard-debug-androidTest.apk clientapi:clientapi-standard-debug-androidTest.apk
                artifacts:
                    - ci/pipeline/test-reports/**

######################################################################
# Define the different pipelines flows as anchors.
######################################################################
flows:
    -   flow: &main-flow
            -   parallel:
                    -   step: *run-clientapi-unit-tests
                    # -   step: *run-id-unit-tests
                    # -   step: *run-face-unit-tests
                    # -   step: *run-fingerprint-unit-tests
                    # -   step: *run-fingerprintscanner-unit-tests
                    # -   step: *build-and-sign-universal-apk
            -   parallel:
                    -   step: *upload-sonar-scan-and-check-quality-gate
                    -   step: *run-all-android-tests

######################################################################
# Define the triggers that launch the pipeline.
######################################################################
pipelines:
    branches:
        master: *main-flow
        develop: *main-flow
        ci/*: *main-flow
    custom:
        default-pipeline: *main-flow # Pipeline that can be triggered manually anywhere
