# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
    depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
    caches:
        gradlewrapper: ~/.gradle/wrapper
    steps:

        ######################################################################
        # Run the Client API unit tests with coverage and upload report to
        # artifacts.
        ######################################################################
        -   step: &run-clientapi-unit-tests
                name: "Run Clientapi unit tests"
                max-time: 30
                size: 2x
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew clientapi:jacocoTestReportStandardDebug
                artifacts:
                    - clientapi/build/reports/**

        ######################################################################
        # Run the ID unit tests with coverage and upload report to artifacts.
        ######################################################################
        -   step: &run-id-unit-tests
                name: "Run Id & Core unit tests"
                size: 2x
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew core:jacocoTestReportDebug
                    - ./gradlew id:jacocoTestReportStandardDebug
                artifacts:
                    - id/build/reports/**
                    - core/build/reports/**

        ######################################################################
        # Run the Face unit tests with coverage and upload report to artifacts.
        ######################################################################
        -   step: &run-face-unit-tests
                name: "Run Face unit tests"
                max-time: 30
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew face:jacocoTestReportStandardDebug
                artifacts:
                    - face/build/reports/**

        ######################################################################
        # Run the Fingerprint unit tests with coverage and upload report to
        # artifacts.
        ######################################################################
        -   step: &run-fingerprint-unit-tests
                name: "Run Fingerprint unit tests"
                max-time: 30
                size: 2x
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew fingerprint:jacocoTestReportStandardDebug
                artifacts:
                    - fingerprint/build/reports/**

        ######################################################################
        # Run the Fingerprint Scanner unit tests with coverage and upload
        # report to artifacts.
        ######################################################################
        -   step: &run-fingerprintscanner-unit-tests
                name: "Run Fingerprint Scanner unit tests"
                max-time: 30
                size: 2x
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew fingerprintscanner:jacocoTestReportDebug
                artifacts:
                    - fingerprintscanner/build/reports/**

        ######################################################################
        # Get all of the test and coverage reports from artifacts, upload
        # them to sonarcloud.io, and check that they pass the quality gateway.
        # Sonarcloud requires Java 11 for the analysis. 
        ######################################################################
        -   step: &upload-sonar-scan-and-check-quality-gate
                max-time: 30
                size: 2x
                name: "Upload scan and check quality gateway"
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - ./gradlew assembleStandardDebug
                    - bash ./ci/pipeline/install_java_11
                    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
                    - ./gradlew sonarqube -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=3600

        ######################################################################
        # Build all of the test APKs for the different modules, then Download
        # the google bundle tool, and use it to create an universal
        # APK and upload it to artifacts.
        ######################################################################
        -   step: &build-and-sign-universal-apk
                name: "Build universal & test APKs"
                max-time: 30
                size: 2x
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    # Build ID Android Test APK
                    - ./gradlew id:assembleStandardDebugAndroidTest
                    - mv id/build/outputs/apk/androidTest/standard/debug/id-standard-debug-androidTest.apk id-standard-debug-androidTest.apk
                    # Build Client API Android Test APK
                    - ./gradlew clientapi:assembleStandardDebugAndroidTest
                    - mv clientapi/build/outputs/apk/androidTest/standard/debug/clientapi-standard-debug-androidTest.apk clientapi-standard-debug-androidTest.apk
                    # Build Fingerprint Android Test APK
                    - ./gradlew fingerprint:assembleStandardDebugAndroidTest
                    - mv fingerprint/build/outputs/apk/androidTest/standard/debug/fingerprint-standard-debug-androidTest.apk fingerprint-standard-debug-androidTest.apk
                    # Build Face Android Test APK
                    - ./gradlew face:assembleStandardDebugAndroidTest
                    - mv face/build/outputs/apk/androidTest/standard/debug/face-standard-debug-androidTest.apk face-standard-debug-androidTest.apk
                    # Build Universal APK
                    - ./gradlew bundleStandardDebug --stacktrace
                    - wget "https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all.jar"
                    - java -jar bundletool-all.jar build-apks --bundle id/build/outputs/bundle/standardDebug/id-standard-debug.aab --output universal.apks --overwrite --mode=UNIVERSAL --ks=debug.keystore --ks-key-alias=androiddebugkey --key-pass=pass:android --ks-pass=pass:android
                    - mv universal.apks universal.zip
                    - unzip universal.zip
                artifacts:
                    - universal.apk
                    - id-standard-debug-androidTest.apk
                    - clientapi-standard-debug-androidTest.apk
                    - fingerprint-standard-debug-androidTest.apk
                    - face-standard-debug-androidTest.apk

        ######################################################################
        # Run All Android tests on Firebase test lab.
        ######################################################################
        -   step: &run-all-android-tests
                name: "Run android tests"
                max-time: 60
                image: google/cloud-sdk:slim
                script:
                    - bash ./ci/pipeline/setup_gcloud
                    - mv ./*.apk ./ci/pipeline/
                    - cd ./ci/pipeline/
                    - ./run_all_android_tests.sh universal.apk id:id-standard-debug-androidTest.apk fingerprint:fingerprint-standard-debug-androidTest.apk face:face-standard-debug-androidTest.apk clientapi:clientapi-standard-debug-androidTest.apk
                artifacts:
                    - ci/pipeline/test-reports/**

        ######################################################################
        # Build a signed bundle with the Playstore upload key, and deploy it
        # to the internal test track. Also upload the bundle and the relevant
        # output files to artifacts.
        #
        # Signing vars are only available on a deployment step.
        ######################################################################
        -   step: &sign-and-deploy-to-internal
                name: "Sign & Deploy to Internal Track"
                deployment: Internal
                max-time: 30
                size: 2x
                trigger: manual
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - bash ./ci/pipeline/release_setup
                    - echo $GOOGLE_API_KEY_JSON > google_api_key.json
                    - echo "BUNDLE_FOLDER=standardStaging" >>ci/deploy.properties
                    - ./gradlew bundleStandardStaging
                    - ./gradlew id:publishStandardStagingBundle
                artifacts:
                    - id/build/outputs/**

        ######################################################################
        # Promote an Internal build to the Closed Alpha Track. This step does
        # not build the signed APK, it just promotes the existing Internal
        # deployment via the Play Store API.
        ######################################################################
        -   step: &release-to-alpha
                name: "Promote Internal to Alpha"
                deployment: Alpha
                max-time: 30
                trigger: manual
                caches:
                    - gradle
                    - gradlewrapper
                script:
                    - bash ./ci/pipeline/setup
                    - bash ./ci/pipeline/release_setup
                    - echo $GOOGLE_API_KEY_JSON > google_api_key.json
                    - echo "BUNDLE_FOLDER=standardRelease" >>ci/deploy.properties
                    - ./gradlew bundleStandardRelease
                    - ./gradlew id:publishStandardReleaseBundle

######################################################################
# Define the different pipelines flows as anchors.
######################################################################
flows:
    -   flow: &main-flow
            -   parallel:
                    -   step: *run-clientapi-unit-tests
                    -   step: *run-id-unit-tests
                    -   step: *run-face-unit-tests
                    -   step: *run-fingerprint-unit-tests
                    -   step: *run-fingerprintscanner-unit-tests
                    -   step: *build-and-sign-universal-apk
            -   parallel:
                    -   step: *upload-sonar-scan-and-check-quality-gate
                    -   step: *run-all-android-tests
    -   flow: &deploy-flow
            -   parallel:
                    -   step: *run-clientapi-unit-tests
                    -   step: *run-id-unit-tests
                    -   step: *run-face-unit-tests
                    -   step: *run-fingerprint-unit-tests
                    -   step: *run-fingerprintscanner-unit-tests
                    -   step: *build-and-sign-universal-apk
            -   parallel:
                    -   step: *upload-sonar-scan-and-check-quality-gate
                    -   step: *run-all-android-tests
            -   step: *sign-and-deploy-to-internal
    -   flow: &release-flow
            -   parallel:
                    -   step: *run-clientapi-unit-tests
                    -   step: *run-id-unit-tests
                    -   step: *run-face-unit-tests
                    -   step: *run-fingerprint-unit-tests
                    -   step: *run-fingerprintscanner-unit-tests
                    -   step: *build-and-sign-universal-apk
            -   parallel:
                    -   step: *upload-sonar-scan-and-check-quality-gate
                    -   step: *run-all-android-tests
            -   step: *release-to-alpha
    -   flow: &ci-test
            -   step: *run-fingerprintscanner-unit-tests

######################################################################
# Define the triggers that launch the pipeline.
######################################################################
pipelines:
    branches:
        master: *release-flow
        develop: *main-flow
        release/*: *deploy-flow
        ci/*: *ci-test
    custom:
        default-pipeline: *main-flow # Pipeline that can be triggered manually anywhere
