#!/usr/bin/env bash
rm -rf /tmp/Android-Cerberus && echo "Android-Cerberus"
git clone -b develop git@github.com:Simprints/Android-Cerberus.git /tmp/Android-Cerberus  && echo "Android-Cerberus cloned"
echo "Files in Android-Cerberus: $(ls -1 /tmp/Android-Cerberus | wc -l)"
python3.6 ./instrumented_test.py  && echo "Done"
rm -rf /tmp/Android-Cerberus && echo "Android-Cerberus"
