package com.simprints.clientapi.clientrequests.validators

import com.simprints.clientapi.mockextractors.MockEnrollmentFactory

class EnrollmentValidatorTest : ClientRequestValidatorTest(MockEnrollmentFactory)
