/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_embedded_artwork {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_embedded_artwork(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_embedded_artwork obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_embedded_artwork(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCartoon(float value) {
    rocJNI.roc_embedded_artwork_cartoon_set(swigCPtr, this, value);
  }

  public float getCartoon() {
    return rocJNI.roc_embedded_artwork_cartoon_get(swigCPtr, this);
  }

  public void setHuman(float value) {
    rocJNI.roc_embedded_artwork_human_set(swigCPtr, this, value);
  }

  public float getHuman() {
    return rocJNI.roc_embedded_artwork_human_get(swigCPtr, this);
  }

  public void setPainting(float value) {
    rocJNI.roc_embedded_artwork_painting_set(swigCPtr, this, value);
  }

  public float getPainting() {
    return rocJNI.roc_embedded_artwork_painting_get(swigCPtr, this);
  }

  public roc_embedded_artwork() {
    this(rocJNI.new_roc_embedded_artwork(), true);
  }

}
