/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public final class roc_pose {
  public final static int ROC_POSE_FRONTAL = rocJNI.ROC_POSE_FRONTAL_get();
  public final static int ROC_POSE_LEFT_PROFILE = rocJNI.ROC_POSE_LEFT_PROFILE_get();
  public final static int ROC_POSE_RIGHT_PROFILE = rocJNI.ROC_POSE_RIGHT_PROFILE_get();
  public final static int ROC_POSE_NUM_POSES = rocJNI.ROC_POSE_NUM_POSES_get();
}

