/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_embedded_mask {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_embedded_mask(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_embedded_mask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_embedded_mask(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMask(float value) {
    rocJNI.roc_embedded_mask_mask_set(swigCPtr, this, value);
  }

  public float getMask() {
    return rocJNI.roc_embedded_mask_mask_get(swigCPtr, this);
  }

  public void setNo_mask(float value) {
    rocJNI.roc_embedded_mask_no_mask_set(swigCPtr, this, value);
  }

  public float getNo_mask() {
    return rocJNI.roc_embedded_mask_no_mask_get(swigCPtr, this);
  }

  public roc_embedded_mask() {
    this(rocJNI.new_roc_embedded_mask(), true);
  }

}
