/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_image {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public roc_image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(roc_image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    rocJNI.roc_image_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = rocJNI.roc_image_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setWidth(long value) {
    rocJNI.roc_image_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return rocJNI.roc_image_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    rocJNI.roc_image_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return rocJNI.roc_image_height_get(swigCPtr, this);
  }

  public void setStep(long value) {
    rocJNI.roc_image_step_set(swigCPtr, this, value);
  }

  public long getStep() {
    return rocJNI.roc_image_step_get(swigCPtr, this);
  }

  public void setColor_space(int value) {
    rocJNI.roc_image_color_space_set(swigCPtr, this, value);
  }

  public int getColor_space() {
    return rocJNI.roc_image_color_space_get(swigCPtr, this);
  }

  public void setMedia_id(roc_hash value) {
    rocJNI.roc_image_media_id_set(swigCPtr, this, roc_hash.getCPtr(value), value);
  }

  public roc_hash getMedia_id() {
    long cPtr = rocJNI.roc_image_media_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new roc_hash(cPtr, false);
  }

  public void setTimestamp(java.math.BigInteger value) {
    rocJNI.roc_image_timestamp_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTimestamp() {
    return rocJNI.roc_image_timestamp_get(swigCPtr, this);
  }

  public roc_image() {
    this(rocJNI.new_roc_image(), true);
  }

}
