/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public final class roc_embedded_error {
  public final static int ROC_NOT_SUPPORTED = rocJNI.ROC_NOT_SUPPORTED_get();
  public final static int ROC_SUCCESS = rocJNI.ROC_SUCCESS_get();
  public final static int ROC_ERROR_LICENSE = rocJNI.ROC_ERROR_LICENSE_get();
  public final static int ROC_ERROR_MALLOC = rocJNI.ROC_ERROR_MALLOC_get();
  public final static int ROC_ERROR_COLORSPACE = rocJNI.ROC_ERROR_COLORSPACE_get();
}

