/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_embedded_geographic_origin {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected roc_embedded_geographic_origin(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(roc_embedded_geographic_origin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_embedded_geographic_origin(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAfrican(float value) {
    rocJNI.roc_embedded_geographic_origin_african_set(swigCPtr, this, value);
  }

  public float getAfrican() {
    return rocJNI.roc_embedded_geographic_origin_african_get(swigCPtr, this);
  }

  public void setEuropean(float value) {
    rocJNI.roc_embedded_geographic_origin_european_set(swigCPtr, this, value);
  }

  public float getEuropean() {
    return rocJNI.roc_embedded_geographic_origin_european_get(swigCPtr, this);
  }

  public void setEast_asian(float value) {
    rocJNI.roc_embedded_geographic_origin_east_asian_set(swigCPtr, this, value);
  }

  public float getEast_asian() {
    return rocJNI.roc_embedded_geographic_origin_east_asian_get(swigCPtr, this);
  }

  public void setSouth_asian(float value) {
    rocJNI.roc_embedded_geographic_origin_south_asian_set(swigCPtr, this, value);
  }

  public float getSouth_asian() {
    return rocJNI.roc_embedded_geographic_origin_south_asian_get(swigCPtr, this);
  }

  public roc_embedded_geographic_origin() {
    this(rocJNI.new_roc_embedded_geographic_origin(), true);
  }

}
