/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public final class roc_algorithm_options {
  public final static int ROC_FRONTAL = rocJNI.ROC_FRONTAL_get();
  public final static int ROC_FULL = rocJNI.ROC_FULL_get();
  public final static int ROC_PERIOCULAR = rocJNI.ROC_PERIOCULAR_get();
  public final static int ROC_MANUAL = rocJNI.ROC_MANUAL_get();
  public final static int ROC_ROLL = rocJNI.ROC_ROLL_get();
  public final static int ROC_FR = rocJNI.ROC_FR_get();
  public final static int ROC_FR_FAST = rocJNI.ROC_FR_FAST_get();
  public final static int ROC_FR_PERIOCULAR = rocJNI.ROC_FR_PERIOCULAR_get();
  public final static int ROC_TATTOO = rocJNI.ROC_TATTOO_get();
  public final static int ROC_PAD_LOGO = rocJNI.ROC_PAD_LOGO_get();
  public final static int ROC_PITCHYAW = rocJNI.ROC_PITCHYAW_get();
  public final static int ROC_DEMOGRAPHICS = rocJNI.ROC_DEMOGRAPHICS_get();
  public final static int ROC_LANDMARKS = rocJNI.ROC_LANDMARKS_get();
  public final static int ROC_LIPS = rocJNI.ROC_LIPS_get();
  public final static int ROC_THUMBNAIL = rocJNI.ROC_THUMBNAIL_get();
  public final static int ROC_INVALID = rocJNI.ROC_INVALID_get();
  public final static int ROC_SPOOF_FF = rocJNI.ROC_SPOOF_FF_get();
  public final static int ROC_SPOOF_AF = rocJNI.ROC_SPOOF_AF_get();
  public final static int ROC_SERIAL = rocJNI.ROC_SERIAL_get();
  public final static int ROC_TEMPLATE_VERSION = rocJNI.ROC_TEMPLATE_VERSION_get();
  public final static int ROC_FR_COMPATIBILITY_VERSION = rocJNI.ROC_FR_COMPATIBILITY_VERSION_get();
  public final static int ROC_TATTOO_COMPATIBILITY_VERSION = rocJNI.ROC_TATTOO_COMPATIBILITY_VERSION_get();
  public final static int ROC_TEMPLATE_VERSION_MASK = rocJNI.ROC_TEMPLATE_VERSION_MASK_get();
}

