/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public class roc_detection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected roc_detection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(roc_detection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rocJNI.delete_roc_detection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    rocJNI.roc_detection_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return rocJNI.roc_detection_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    rocJNI.roc_detection_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return rocJNI.roc_detection_y_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    rocJNI.roc_detection_width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return rocJNI.roc_detection_width_get(swigCPtr, this);
  }

  public void setHeight(float value) {
    rocJNI.roc_detection_height_set(swigCPtr, this, value);
  }

  public float getHeight() {
    return rocJNI.roc_detection_height_get(swigCPtr, this);
  }

  public void setRotation(float value) {
    rocJNI.roc_detection_rotation_set(swigCPtr, this, value);
  }

  public float getRotation() {
    return rocJNI.roc_detection_rotation_get(swigCPtr, this);
  }

  public void setConfidence(float value) {
    rocJNI.roc_detection_confidence_set(swigCPtr, this, value);
  }

  public float getConfidence() {
    return rocJNI.roc_detection_confidence_get(swigCPtr, this);
  }

  public void setPose(int value) {
    rocJNI.roc_detection_pose_set(swigCPtr, this, value);
  }

  public int getPose() {
    return rocJNI.roc_detection_pose_get(swigCPtr, this);
  }

  public roc_detection() {
    this(rocJNI.new_roc_detection(), true);
  }

}
