/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rankone.rocsdk.embedded;

public interface rocConstants {
  public final static int ROC_VERSION_MAJOR = rocJNI.ROC_VERSION_MAJOR_get();
  public final static int ROC_VERSION_MINOR = rocJNI.ROC_VERSION_MINOR_get();
  public final static int ROC_VERSION_PATCH = rocJNI.ROC_VERSION_PATCH_get();
  public final static String ROC_VERSION_STRING = rocJNI.ROC_VERSION_STRING_get();
  public final static String ROC_COPYRIGHT = rocJNI.ROC_COPYRIGHT_get();
  public final static float ROC_SUGGESTED_RELATIVE_MIN_SIZE = rocJNI.ROC_SUGGESTED_RELATIVE_MIN_SIZE_get();
  public final static long ROC_SUGGESTED_ABSOLUTE_MIN_SIZE = rocJNI.ROC_SUGGESTED_ABSOLUTE_MIN_SIZE_get();
  public final static float ROC_SUGGESTED_FALSE_DETECTION_RATE = rocJNI.ROC_SUGGESTED_FALSE_DETECTION_RATE_get();
  public final static java.math.BigInteger ROC_NO_TIMESTAMP = rocJNI.ROC_NO_TIMESTAMP_get();
  public final static long ROC_STANDARD_FV_SIZE = rocJNI.ROC_STANDARD_FV_SIZE_get();
  public final static long ROC_FAST_FV_SIZE = rocJNI.ROC_FAST_FV_SIZE_get();
  public final static long ROC_PERIOCULAR_FV_SIZE = rocJNI.ROC_PERIOCULAR_FV_SIZE_get();
  public final static long ROC_TATTOO_FV_SIZE = rocJNI.ROC_TATTOO_FV_SIZE_get();
  public final static float ROC_MAX_SIMILARITY = rocJNI.ROC_MAX_SIMILARITY_get();
  public final static float ROC_MIN_SIMILARITY = rocJNI.ROC_MIN_SIMILARITY_get();
  public final static float ROC_INVALID_SIMILARITY = rocJNI.ROC_INVALID_SIMILARITY_get();
  public final static float ROC_DEFAULT_SEARCH_THRESHOLD = rocJNI.ROC_DEFAULT_SEARCH_THRESHOLD_get();
  public final static float ROC_DEFAULT_VERIFICATION_THRESHOLD = rocJNI.ROC_DEFAULT_VERIFICATION_THRESHOLD_get();
}
