package com.simprints.fingerprint.exceptions.unexpected.request

import com.simprints.fingerprint.exceptions.unexpected.FingerprintUnexpectedException

class InvalidRequestForCollectFingerprintsActivityException(message: String = "InvalidRequestForCollectFingerprintsActivityException") : FingerprintUnexpectedException(message)
