package com.simprints.id.activities;

public enum ALERT_TYPE {
    MISSING_API_KEY,
    INVALID_API_KEY,

    BLUETOOTH_NOT_SUPPORTED,
    BLUETOOTH_NOT_ENABLED,
    BLUETOOTH_UNBONDED_SCANNER,

    NO_SCANNER_FOUND,
    MULTIPLE_SCANNERS_FOUND,

    UNEXPECTED_ERROR
}
