#!/bin/bash

ANDROID_COMPILE_SDK=30
ANDROID_BUILD_TOOLS=30.0.2
ANDROID_SDK_TOOLS=7583922

apt-get install -y unzip make expect # NDK stuff		

SDK_MANAGER="$PWD/android/cmdline-tools/tools/bin/sdkmanager"

echo "sdk.dir=$PWD/android" >> local.properties

mkdir android
cd android || exit
wget -nv https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
unzip -q -d cmdline-tools commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
mv cmdline-tools/cmdline-tools cmdline-tools/tools

echo y | $SDK_MANAGER "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" --sdk_root="./"
echo y | $SDK_MANAGER "build-tools;${ANDROID_BUILD_TOOLS}" --sdk_root="./"
echo y | $SDK_MANAGER ndk-bundle --sdk_root="./"

yes | $SDK_MANAGER --licenses
