package com.simprints.fingerprint.exceptions.unexpected.request

import com.simprints.fingerprint.exceptions.unexpected.FingerprintUnexpectedException

class InvalidRequestForConnectScannerActivityException(message: String = "InvalidRequestForConnectScannerActivityException") : FingerprintUnexpectedException(message)
