#!/bin/bash
# clone dependabot scripts repo which we’ll need later on to run our Docker image.
git clone https://github.com/meladRaouf/dependabot-script.git
cd dependabot-script

# Set env variables
export PROJECT_PATH=simprints/android-simprints-id
export PACKAGE_MANAGER=gradle
export BRANCH=develop
export BITBUCKET_APP_PASSWORD=${BITBUCKET_BOT_APP_PASSWORD}
export BITBUCKET_APP_USERNAME=${BITBUCKET_BOT_USERNAME}


#Build dependabot-script
bundle  install

# dependabot core tries to add label in bitbucket pull request creation which is not supported yet
# by bitbucket, so we disable this behavior by passing nil instead of labeler object.
#More details are in this PR https://github.com/dependabot/dependabot-core/pull/4236

sed -i '85s/.*/\tnil,/' /usr/local/bundle/gems/dependabot-common-0.162.0/lib/dependabot/pull_request_creator/bitbucket.rb

# Run dependabot
bundle exec ruby ./generic-update-script.rb
