#!/bin/bash
# clone dependabot scripts repo which we’ll need later on to run our Docker image.
git clone https://github.com/meladRaouf/dependabot-script.git
cd dependabot-script

# Set env variables
export PROJECT_PATH=simprints/android-simprints-id
export PACKAGE_MANAGER=gradle
export BRANCH=main
export BITBUCKET_APP_PASSWORD=${BITBUCKET_BOT_APP_PASSWORD}
export BITBUCKET_APP_USERNAME=${BITBUCKET_BOT_USERNAME}


#Build dependabot-script
bundle  install

# Run dependabot
bundle exec ruby ./generic-update-script.rb
