#!/bin/bash

# Get the input parameters
VERSION_SUFFIX=${1:-""}
DEBUGGABLE=${2:-"false"}
DB_ENCRYPTION=${3:-"false"}


# Get the branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Extract the VERSION_NAME from the branch name if the branch name starts with release
if [[ $BRANCH_NAME =~ ^release\/ ]]; then
  VERSION_NAME=${BRANCH_NAME#release\/}
else
  # Read the VERSION_NAME from the env variable VERSION_NAME
  VERSION_NAME=${VERSION_NAME:-"0.0.0"}
fi

# Get the current timestamp
TIMESTAMP=$(date +%s)

# Calculate the VERSION_CODE
VERSION_CODE=$((TIMESTAMP / 1000))

#overwrite the existing file with an empty file
truncate -s 0 build-logic/build_properties.gradle.kts
#Write the build properties
cat << EOF >> build-logic/build_properties.gradle.kts
extra.apply {
    set("VERSION_CODE", $VERSION_CODE)
    set("VERSION_NAME", "$VERSION_NAME")
    set("VERSION_SUFFIX", "$VERSION_SUFFIX")
    set("DEBUGGABLE", $DEBUGGABLE)
    set("DB_ENCRYPTION", $DB_ENCRYPTION)
}
EOF

echo "Wrote build_properties.gradle.kts file with VERSION_NAME='$VERSION_NAME', VERSION_CODE='$VERSION_CODE', VERSION_SUFFIX='$VERSION_SUFFIX', DEBUGGABLE='$DEBUGGABLE', and DB_ENCRYPTION='$DB_ENCRYPTION'"

