#!/bin/bash

# Get the branch name after the last '/'. ex release/2020.4.0 = 2020.4.0
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

var_branchSuffix=$(echo "$BRANCH_NAME" | sed 's:.*/::')

# We use force in case we are moving this tag from a previous release.
git tag --force "v$var_branchSuffix"
git push --force --tags
