#!/bin/bash

echo "$SIGNING_JKS_FILE" | base64 -di >android-signing-keystore.jks

cat << EOF >> build-logic/signing_properties.gradle.kts
extra.apply {
    set("store_file", "\$rootDir/android-signing-keystore.jks")
    set("store_password", "${SIGNING_KEYSTORE_PASSWORD}")
    set("key_alias", "${SIGNING_KEY_ALIAS}")
    set("key_password", "${SIGNING_KEY_PASSWORD}")
}
EOF
