#!/bin/bash

if [ -z "$BITBUCKET_PR_DESTINATION_BRANCH" ]; then
    echo "Not a pull request, skipping target branch pull"
    echo "FOR NOW PULL ANYWAYS"
    git fetch +refs/heads/master:refs/remotes/origin/master
else
    echo "Pull request aginst $BITBUCKET_PR_DESTINATION_BRANCH"
    git fetch +refs/heads/$BITBUCKET_PR_DESTINATION_BRANCH:refs/remotes/origin/$BITBUCKET_PR_DESTINATION_BRANCH
fi
