#!/bin/bash

echo "storeFile=android-signing-keystore.jks"
echo "storePassword=${SIGNING_KEYSTORE_PASSWORD}" >>buildSrc/keystore.properties
echo "keyAlias=${SIGNING_KEY_ALIAS}" >>buildSrc/keystore.properties
echo "keyPassword=${SIGNING_KEY_PASSWORD}" >>buildSrc/keystore.properties

echo "$SIGNING_JKS_FILE" | base64 -di >android-signing-keystore.jks

echo "VERSION_CODE=${BITBUCKET_BUILD_NUMBER}" >>buildSrc/build.properties
echo "VERSION_SUFFIX=${BITBUCKET_DEPLOYMENT_ENVIRONMENT}" >>buildSrc/build.properties

echo "DEBUGGABLE=false"
