#!/bin/bash

bash ./ci/tools/install_android
bash ./ci/tools/install_java_11
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

echo "org.gradle.caching=true" >>gradle.properties


#########################################################################################
# https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
#########################################################################################
echo "org.gradle.jvmargs=-Xmx6g"

touch /opt/atlassian/pipelines/agent/build/local.properties
