name: "Set Release Git Tag"
description: "Set the release git tag for the current build."

runs:
    using: "composite"

    steps:
        -   name: Set up gradle properties
            shell: bash
            run: |
                # Get the branch name after the last '/'. ex release/2020.4.0 = 2020.4.0
                BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

                var_branchSuffix=$(echo "$BRANCH_NAME" | sed 's:.*/::')

                # We use force in case we are moving this tag from a previous release.
                git tag --force "v$var_branchSuffix"
                git push --force --tags
