name: Deploy to Staging
on:
    # Manual trigger for workflow dispatch (e.g., when clicking "Run workflow" button)
    workflow_dispatch:
        branches:
            - 'release/*'

jobs:
    deploy-to-staging:

        uses: ./.github/workflows/deploy-to-firebase-distribution.yml
        secrets: inherit
        with:
            buildType: staging
