# Deploy APKs to Firebase App Distribution
name: Deploy to Firebase
on:
    workflow_call:
        inputs:
            buildType:
                type: string
                required: true

    workflow_dispatch:
        inputs:
            buildType:
                type: choice
                required: true
                default: dev
                description: "Choose the build variant"
                options:
                    - dev
                    - staging
jobs:
    deploy-to-firebase:
        runs-on: ubuntu-latest

        concurrency:
            group: firebase-${{ inputs.buildType }}-workflow #only one instance of this workflow can run at a time

        environment: ${{ inputs.buildType }}   # Dynamically set the job environment based on the input

        env:
            BUILD_IS_DEBUGGABLE: ${{ vars.BUILD_IS_DEBUGGABLE }}
            DB_IS_ENCRYPTED: ${{ vars.DB_IS_ENCRYPTED }}
            FIREBASE_DIST_CREDENTIALS: ${{ secrets.FIREBASE_DIST_CREDENTIALS}}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Set up local.properties
                run: |
                    source ci/pipeline/setup
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties

            -   name: Update build properties
                run: |
                    source ci/deployment/build_properties_setup ${{ inputs.buildType }} $BUILD_IS_DEBUGGABLE $DB_IS_ENCRYPTED


            -   name: write firebase credentials
                run: echo "$FIREBASE_DIST_CREDENTIALS" >  id/src/main/serviceCredentialsFile.json

            -   name: build and deploy debug apk
                if: ${{ inputs.buildType == 'dev' }}
                run: |
                    ./gradlew id:packageDebugUniversalApk
                    ./gradlew id:appDistributionUploadDebug --artifactPath=id/build/outputs/apk_from_bundle/debug/id-debug-universal.apk

            -   name: build and deploy staging apk
                if: ${{ inputs.buildType == 'staging' }}
                run: |
                    ./gradlew id:packageStagingUniversalApk
                    ./gradlew id:appDistributionUploadStaging  --artifactPath=id/build/outputs/apk_from_bundle/staging/id-staging-universal.apk

            -   name: deploy to firebase completed
                run: echo "### An Apk was deployed into firebase ${{ inputs.buildType }} channel :rocket:" >> $GITHUB_STEP_SUMMARY
