# This workflow build and sign android bundle and uploads it to google play internal testing track

name: Release to Internal

on:
    # Manual trigger for workflow dispatch (e.g., when clicking "Run workflow" button)
    workflow_dispatch:
        branches:
            - 'release/*'
    # Triggered when a push occurs on branches starting with 'release/'
    push:
        branches:
            - 'release/*'
jobs:
    build-and-deploy:

        runs-on: ubuntu-latest

        concurrency:
            group: release-workflow #only one instance of this workflow can run at a time

        permissions:
            contents: write # A write permission For Auto tagging the releases

        environment: internal

        env:
            BUILD_IS_DEBUGGABLE: ${{ vars.BUILD_IS_DEBUGGABLE }}
            DB_IS_ENCRYPTED: ${{ vars.DB_IS_ENCRYPTED }}
            RELEASE_GOOGLE_SERVICES_FILE: ${{ secrets.RELEASE_GOOGLE_SERVICES_FILE}}
            GOOGLE_API_KEY_JSON: ${{secrets.GOOGLE_API_KEY_JSON}}

            SIGNING_JKS_FILE: ${{secrets.SIGNING_JKS_FILE}}
            SIGNING_KEYSTORE_PASSWORD: ${{secrets.SIGNING_KEYSTORE_PASSWORD}}
            SIGNING_KEY_ALIAS: ${{secrets.SIGNING_KEY_ALIAS}}
            SIGNING_KEY_PASSWORD: ${{secrets.SIGNING_KEY_PASSWORD}}

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   name: Set up Gradle
                uses: gradle/gradle-build-action@v2

            -   name: setup local.properties
                run: |
                    source ci/pipeline/setup
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties

            -   name: Update build properties
                run: |
                    source ci/deployment/build_properties_setup Internal  $BUILD_IS_DEBUGGABLE $DB_IS_ENCRYPTED

            -   name: write Google API key file # This file needed by triplet the google play publishing lib
                run: echo "$GOOGLE_API_KEY_JSON" >google_api_key.json

            -   name: Write Google Services file
                run: echo $RELEASE_GOOGLE_SERVICES_FILE > id/src/release/google-services.json

            -   name: Set up signing properties
                run: source ci/deployment/signing_properties_setup

            -   name: Build and deploy Release bundle
                run: ./gradlew id:bundleRelease

            -   name: Publish Release bundle
                run: ./gradlew id:publishReleaseBundle

            -   name: Set release tag
                run: bash ci/deployment/release_tag_setup
