# Deploy APKs to Firebase App Distribution
name: Deploy to Firebase
on:
    workflow_call:
        inputs:
            buildType:
                type: string
                required: true

    workflow_dispatch:
        inputs:
            buildType:
                type: choice
                required: true
                default: dev
                options:
                    - dev
                    - staging
jobs:
    deploy:
        runs-on: ubuntu-latest

        concurrency:
            group: firebase-${{ inputs.buildType }}-workflow #only one instance of this workflow can run at a time

        environment: ${{ inputs.buildType }}

        env:
            BUILD_IS_DEBUGGABLE: ${{ vars.BUILD_IS_DEBUGGABLE }}
            DB_IS_ENCRYPTED: ${{ vars.DB_IS_ENCRYPTED }}
            FIREBASE_DIST_CREDENTIALS: ${{ secrets.FIREBASE_DIST_CREDENTIALS}}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   name: Set up Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Set up local.properties
                run: |
                    source ci/pipeline/setup
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties

            -   name: Update build properties
                run: |
                    source ci/deployment/build_properties_setup ${{ inputs.buildType }} $BUILD_IS_DEBUGGABLE $DB_IS_ENCRYPTED


            -   name: write firebase credentials
                run: echo "$FIREBASE_DIST_CREDENTIALS" >  id/src/main/serviceCredentialsFile.json

            -   name: build apk
                run: |
                    #check if the build type is dev or staging
                    if [ "${{ inputs.buildType }}" = "dev" ]; then
                        ./gradlew id:packageDebugUniversalApk
                    else
                        ./gradlew id:packageStagingUniversalApk
                    fi

            -   name: deploy to firebase
                run: |
                    #check if the build type is dev or staging
                    if [ "${{ inputs.buildType }}" = "dev" ]; then
                        ./gradlew id:appDistributionUploadDebug --artifactPath=id/build/outputs/apk_from_bundle/debug/id-debug-universal.apk
                    else
                        ./gradlew id:appDistributionUploadStaging  --artifactPath=id/build/outputs/apk_from_bundle/staging/id-staging-universal.apk    
                    fi
                    echo "### An Apk was deployed into firebase ${{ inputs.buildType }} channel :rocket:" >> $GITHUB_STEP_SUMMARY
