# Auto create jira task for github issues
name: Jira Sync

on:
    workflow_dispatch:


# [TODO] enable this workflow once the jira integration is ready
#    issues:
#        types: [ opened, labeled, unlabeled ]
#    issue_comment:
#        types: [ created ]
jobs:
    sync:
        name: Sync Items
        runs-on: ubuntu-latest
        timeout-minutes: ${{ fromJSON(vars.JOB_TIMEOUT_MINUTES) }}
        steps:
            -   name: Sync
                uses: mheap/github-action-issue-to-jira@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    jiraHost: ${{ secrets.JIRA_HOST }}
                    jiraUsername: ${{ secrets.JIRA_USERNAME }}
                    jiraPassword: ${{ secrets.JIRA_PASSWORD }}
                    project: ${{ vars.JIRA_PROJECT_KEY }}
                    assignee: ${{ vars.JIRA_ASSIGNEE }}
