name: "[Pipeline] Deploy to Dev"

on:
    workflow_call:

jobs:

    get-version:
        uses: ./.github/workflows/reusable-get-version-name.yml
        with:
            version-source: "internal"

    build-dev-apk:
        uses: ./.github/workflows/reusable-build-apk.yml
        secrets: inherit
        needs: get-version
        with:
            build-environment: dev
            version-name: ${{ needs.get-version.outputs.version-name }}

    deploy-to-firebase:
        uses: ./.github/workflows/reusable-deploy-to-firebase-distribution.yml
        secrets: inherit
        needs:
            - build-dev-apk
        with:
            build-environment: dev
            upload-artifact: ${{ needs.build-dev-apk.outputs.build-artifact }}
