name: "[Pipeline] Deploy to Internal"

on:
    workflow_call:

jobs:

    get-version:
        uses: ./.github/workflows/reusable-get-version-name.yml
        with:
            version-source: "branch"

    build-internal-aab:
        uses: ./.github/workflows/reusable-build-apk.yml
        secrets: inherit
        needs: get-version
        with:
            build-environment: Internal
            version-name: ${{ needs.get-version.outputs.version-name }}

    run-app-sweep:
        uses: ./.github/workflows/reusable-app-sweep.yml
        with:
            upload-artifact: ${{ needs.build-internal-aab.outputs.build-artifact }}
            mapping-file: ${{ needs.build-internal-aab.outputs.optional-mapping-file }}
        secrets: inherit
        needs:
            - build-internal-aab

    deploy-internal-build:
        uses: ./.github/workflows/reusable-promote-artifact.yml
        secrets: inherit
        with:
            deployment-track: Internal
            upload-artifact: ${{ needs.build-internal-aab.outputs.build-artifact }}
            mapping-file: ${{ needs.build-internal-aab.outputs.optional-mapping-file }}
        needs:
            - build-internal-aab
