
name: "[Pipeline] Deploy to Dev"

on:
    workflow_call:

jobs:
    build-dev-apk:
        environment: dev
        runs-on: ubuntu-latest


    deploy-to-dev:
        uses: ./.github/workflows/reusable-deploy-to-firebase-distribution.yml
        secrets: inherit
        with:
            buildType: dev
