name: "[Pipeline] Deploy to Dev"

on:
    workflow_call:

jobs:

    extract-version-name:
        runs-on: ubuntu-latest

        outputs:
            version-name: ${{ steps.extract-version-name.outputs.version-name }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Extract VERSION_NAME from build_properties.gradle.kts
                id: extract-version-name
                run: |
                    VERSION_NAME=$(grep 'VERSION_NAME' build-logic/build_properties.gradle.kts | awk -F'"' '{print $2}')
                    echo "version-name=$VERSION_NAME" >> $GITHUB_OUTPUT

    build-dev-apk:
        uses: ./.github/workflows/reusable-build-apk.yml
        secrets: inherit
        needs: extract-version-name
        with:
            build-environment: dev
            version-name: ${{ needs.extract-version-name.outputs.version-name }}

    deploy-to-firebase:
        uses: ./.github/workflows/reusable-deploy-to-firebase-distribution.yml
        secrets: inherit
        needs:
            - build-dev-apk
        with:
            build-environment: dev
            upload-artifact: ${{ needs.build-dev-apk.outputs.build-artifact }}
