name: "[Pipeline] Deploy to Internal"

on:
    workflow_call:

jobs:

    get-version:
        uses: ./.github/workflows/reusable-get-version-name.yml
        with:
            version-source: "branch"

    build-internal-aab:
        uses: ./.github/workflows/reusable-build-apk.yml
        secrets: inherit
        needs: get-version
        with:
            build-environment: Internal
            version-name: ${{ needs.get-version.outputs.version-name }}

    upload-to-internal-and-release:
        uses: ./.github/workflows/reusable-upload-to-internal-and-release.yml
        secrets: inherit
        with:
            upload-artifact: ${{ needs.build-internal-aab.outputs.build-artifact }}
            version-name: ${{ needs.get-version.outputs.version-name }}
            version-code: ${{ needs.build-internal-aab.outputs.version-code }}
            mapping-file: ${{ needs.build-internal-aab.outputs.optional-mapping-file }}
        needs:
            - get-version
            - build-internal-aab
