# Upload release apk to App Sweep
name: "[Reusable] App Sweep Security Scan"

on:
    workflow_call:
        inputs:
            upload-artifact:
                type: string
                required: true
            mapping-file:
                type: string
                required: true

jobs:
    app-sweep:
        name: App Sweep Security Scan
        runs-on: ubuntu-latest
        timeout-minutes: ${{ fromJSON(vars.JOB_TIMEOUT_MINUTES) }}
        environment: internal

        steps:
            -   name: Download AAB artifact
                uses: actions/download-artifact@v4
                with:
                    name: ${{ inputs.upload-artifact }}

            -   name: Write mapping text to file
                run: echo "${{ inputs.mapping-file }}" > mapping.txt

            -   name: Upload release apk
                uses: guardsquare/appsweep-action@main
                with:
                    appsweep_api_key: ${{ secrets.APPSWEEP_API_KEY }}
                    input_file: ${{ inputs.upload-artifact }}
                    mapping_file: mapping.txt
                    commit_hash: ${{ github.sha }}
