# Checks if there were merge commits in the last 'days-ago' days
name: "[Reusable] Check if there are recent merges"

on:
    workflow_call:
        inputs:
            days-ago:
                type: number
                description: "Amount of days to look back for merges"
                default: 7

        outputs:
            has-recent-merges:
                description: "True if there were merges in the last 'days-ago' days"
                value: ${{ jobs.check-merges.outputs.has-recent-merges }}

jobs:
    check-merges:
        runs-on: ubuntu-latest

        outputs:
            has-recent-merges: ${{ steps.check-merges.outputs.has-recent-merges }}

        steps:
            -   name: Checkout code (optional, only if you need repo files for other reasons)
                uses: actions/checkout@v5
                with:
                    fetch-depth: 50 # Adjust as needed, 0 for full history

            -   name: Check for recent merges
                id: check-merges
                env:
                    TARGET_BRANCH: ${{ github.ref_name }}
                    DAYS_AGO: ${{ inputs.days-ago }}
                run: |
                    echo "Checking for merges to $TARGET_BRANCH in the last $DAYS_AGO days."

                    cutoff_date_seconds=$(date -v -${DAYS_AGO}d +%s)
                    recent_merge_commit=$(git log $TARGET_BRANCH --merges --since="$DAYS_AGO days ago" --pretty=format:"%ct" -n 1)

                    if [[ -n "$recent_merge_commit" ]]; then
                        if (( $recent_merge_commit > cutoff_date_seconds )); then
                            echo "Found recent merge commit on $TARGET_BRANCH: $commit_hash at $(date -d @$commit_timestamp)"
                            echo "has-recent-merges=true" >> $GITHUB_OUTPUT
                        else
                            echo "No *recent* merge commits found on $TARGET_BRANCH in the last $DAYS_AGO days."
                            echo "has-recent-merges=false" >> $GITHUB_OUTPUT
                        fi
                    else
                        echo "No merge commits found on $TARGET_BRANCH in the last $DAYS_AGO days using 'git log --merges'."
                        echo "has-recent-merges=false" >> $GITHUB_OUTPUT
                    fi
