name: "[Reusable] Build APK"

on:
    workflow_call:
        inputs:
            build-environment:
                type: string
                required: true
        outputs:
            build-artifact:
                type: string
                required: true
                value: ${{ jobs.build-apk.outputs.build-artifact }}

jobs:
    build-apk:

        outputs:
            build-artifact: ${{ steps.set-build-artifact.outputs.artifact }}

        runs-on: ubuntu-latest

        environment: ${{ inputs.build-environment }}

        env:
            # VERSION_CODE: Unique version code using the sum of the current timestamp and run number.
            VERSION_CODE: $(($(date +%s) / 1000 + ${{ github.run_number }}))
            # VERSION_NAME: Version name derived from the GitHub ref name after the final /.
            VERSION_NAME: $(echo '${{ github.ref_name }}' | awk -F'/' '{print $NF}')
            # VERSION_SUFFIX: The build environment (e.g., dev, staging, internal).
            VERSION_SUFFIX: ${{ inputs.build-environment }}
            # VERSION_BUILD: A unique build identifier combining the run number and attempt.
            VERSION_BUILD: ${{ github.run_number }}.${{ github.run_attempt }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   name: Set up local.properties
                run: |
                    #!/bin/bash
                    chmod +x gradlew
                    echo "org.gradle.caching=true" >>gradle.properties
                    echo "org.gradle.jvmargs=-Xmx7g"
                    touch local.properties
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties

            -   name: Write Google Services file
                run: echo ${{ secrets.GOOGLE_SERVICES_FILE}} > id/src/google-services.json

            -   name: Create build properties
                run: |
                    #overwrite the existing file with an empty file
                    truncate -s 0 build-logic/build_properties.gradle.kts
                    #Write the build properties
                    cat <<EOF >>build-logic/build_properties.gradle.kts
                    extra.apply {
                        set("VERSION_CODE", $VERSION_CODE)
                        set("VERSION_NAME", "$VERSION_NAME")
                        set("VERSION_SUFFIX", "$VERSION_SUFFIX")
                        set("VERSION_BUILD", "$VERSION_BUILD")
                        set("DEBUGGABLE", ${{ vars.BUILD_IS_DEBUGGABLE }})
                        set("DB_ENCRYPTION", ${{ vars.DB_IS_ENCRYPTED }})
                    }
                    EOF

            -   name: write firebase credentials
                run: echo "${{ secrets.FIREBASE_DIST_CREDENTIALS}}" >  id/src/serviceCredentialsFile.json

            -   name: Set up signing properties
                run: |
                    #!/bin/bash
                    echo "${{secrets.SIGNING_JKS_FILE}}" | base64 -di >android-signing-keystore.jks
                    #overwrite or crate the file with an empty file
                    truncate -s 0 build-logic/signing_info.gradle.kts
                    cat << EOF >> build-logic/signing_info.gradle.kts
                    extra.apply {
                        set("store_file", "\$rootDir/android-signing-keystore.jks")
                        set("store_password", "${{secrets.SIGNING_KEYSTORE_PASSWORD}}")
                        set("key_alias", "${{secrets.SIGNING_KEY_ALIAS}}")
                        set("key_password", "${{secrets.SIGNING_KEY_PASSWORD}}")
                    }
                    EOF

            -   name: build dev apk
                if: ${{ inputs.build-environment == 'dev' }}
                run: |
                    ./gradlew id:packageDebugUniversalApk

            -   name: build staging apk
                if: ${{ inputs.build-environment != 'staging' }}
                run: |
                    ./gradlew id:packageStagingUniversalApk

            -   name: build internal apk
                if: ${{ inputs.build-environment != 'internal' }}
                run: |
                    ./gradlew id:bundleRelease

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: $VERSION_NAME-$VERSION_SUFFIX+$VERSION_CODE.$VERSION_BUILD
                    path: |
                        id/build/outputs/apk_from_bundle/debug/id-debug-universal.apk
                        id/build/outputs/apk_from_bundle/staging/id-staging-universal.apk
                        id/build/outputs/bundle/release/*.aab

            -   name: Set build-artifact output
                id: set-build-artifact
                run: echo "artifact=$VERSION_NAME-$VERSION_SUFFIX+$VERSION_CODE.$VERSION_BUILD" >> $GITHUB_OUTPUT
