# this job downloads all testing reports then does a sonarqube scan
name: SonarQube Scan
on:
    workflow_call:
    workflow_dispatch:
jobs:
    sonarQube:
        environment: dev
        env:
            BUILD_IS_DEBUGGABLE: ${{ vars.BUILD_IS_DEBUGGABLE }}
            DB_IS_ENCRYPTED: ${{ vars.DB_IS_ENCRYPTED }}
            FIREBASE_DIST_CREDENTIALS: ${{ secrets.FIREBASE_DIST_CREDENTIALS}}
            GOOGLE_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_FILE}}

            SIGNING_JKS_FILE: ${{secrets.SIGNING_JKS_FILE}}
            SIGNING_KEYSTORE_PASSWORD: ${{secrets.SIGNING_KEYSTORE_PASSWORD}}
            SIGNING_KEY_ALIAS: ${{secrets.SIGNING_KEY_ALIAS}}
            SIGNING_KEY_PASSWORD: ${{secrets.SIGNING_KEY_PASSWORD}}

        runs-on: ubuntu-latest
        timeout-minutes: ${{ fromJSON(vars.JOB_TIMEOUT_MINUTES) }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0 # do full git history checkout as this info needed for the sonar plugin
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: 'temurin'


            -   name: Set up local.properties
                run: |
                    source ci/pipeline/setup
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties

            -   name: Write Google Services file
                run: echo $GOOGLE_SERVICES_FILE > id/src/google-services.json

            -   name: Set up signing properties
                run: source ci/deployment/signing_properties_setup


            -   name: run assemble release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    ./gradlew assembleRelease
