# this job downloads all testing reports then does a sonarqube scan
name: SonarQube Scan
on:
    workflow_call:
    workflow_dispatch:
jobs:
    sonarQube:

        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0 # do full git history checkout as this info needed for the sonar plugin
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   name: Restore gradle global directory
                uses: actions/cache/restore@v3
                id: cache
                with:
                    path: |
                        ~/.gradle/
                        .gradle/
                    key: global-gradle-
                    restore-keys: global-gradle-

            -   name: Set up local.properties
                run: |
                    source ci/pipeline/setup
                    echo "GITHUB_USERNAME=${{ secrets.GH_PACKAGE_NAME }}" >>  local.properties
                    echo "GITHUB_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}" >>  local.properties


            -   name: download all artifacts
                uses: actions/download-artifact@v3
                with:
                    path: test-reports
            # Move all reports to the root directory
            # Use -f to force the move and || true to prevent failure if the file doesn't exist
            -   name: Move reports
                run: |
                    rsync -arv test-reports/core/* .  || true
                    rsync -arv test-reports/infra1/* .  || true
                    rsync -arv test-reports/infra2/* .  || true
                    rsync -arv test-reports/feature1/* .  || true
                    rsync -arv test-reports/feature2/* .  || true
                    rsync -arv test-reports/dashboard/* .  || true
                    rsync -arv test-reports/face/* .  || true
                    rsync -arv test-reports/fingerprint/* .  || true

            # list all reports for Id module
            -   name: list reports
                run: |
                    ls -l id


            -   name: run sonar
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    ./gradlew sonar -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=3600 --info
